require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '17.2'

target 'InnerSight' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Disable new architecture for now to resolve build issues
    :new_arch_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
    
    # Fix for build issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.2'
        # Use arm64 for Apple Silicon Macs
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
  end
end